#!/bin/sh
#Generated cli script for application: target/mongock-example-springboot-springdata-annotation-cli-1.0-SNAPSHOT.jar
 java -jar /home/dieppa/dev/projects/mongock-projects/mongock-examples/professional/mongoDB/springboot-springdata-annotation-cli/target/mongock/mongock-example-springboot-springdata-annotation-cli-1.0-SNAPSHOT-mongock-cli.jar "$@"
