#!/bin/sh
#TODO search for a mongock-cli.jar. If it's not in the folder, take the first .jar and copy/past to mongock-cli.jar
#TODO create a separated script, create-mongock-cli.sh, that takes the name of the jar as parameter, copy/past that jar to mongock-cli.jar and update manifest
  cp target/spring5-springdata3-1.0-SNAPSHOT.jar target/mongock-cli.jar
  echo "Start-Class: io.mongock.professional.cli.springboot.MongockSpringbootCli" >> manifest.txt
  jar ufm target/mongock-cli.jar manifest.txt

#  mvn clean install -Pmongock-cli
  java -jar target/mongock-cli.jar "$@"
