#!/bin/sh
#Generated cli script
 java -jar ${project.artifactId}-${project.version}.jar \
 --cli-version ${project.version} \
 --mongock-community-version ${mongock.community.version} \
 --mongock-professional-version ${mongock.pro.version} \
 "$@"  \
  \
