#!/bin/sh
#Generated cli script
 java -jar ${project.artifactId}-${project.version}.jar -cliSpringJar lib/mongock-cli-springboot-${project.version}.jar -cliCoreJar lib/mongock-cli-core-${project.version}.jar "$@"
